jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    password: 1234
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false